# fly.toml app configuration file generated for modmail-autoreply-tmp on 2023-06-11T22:21:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "modmail-autoreply-tmp"
primary_region = "sjc"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = false